version = 0.1
[default.deploy.parameters]
stack_name = "aws-glue-job-tracker"
resolve_s3 = true
s3_prefix = "aws-glue-job-tracker"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GlueJobWorkerThreshold=\"1\" GlueJobDurationThreshold=\"1\" GlueJobNotifications=\"chaejh@amazon.com\""
image_repositories = []
